### ISSUE TITLE
BAD signatures for 4.0.11?

### ISSUE THREAD

**Issue by BigBlockIfTrue** [Electron-Cash/keys-n-hashes#54]
I tried the following GPG commands but surprisingly they returned "BAD signature from Jonald/Calin":

```
gpg --verify JF.Electron-Cash-4.0.11-x86_64.AppImage.asc SHA256.Electron-Cash-4.0.11-x64_64.AppImage.txt
gpg --verify CC.Electron-Cash-4.0.11-x86_64.AppImage.asc SHA256.Electron-Cash-4.0.11-x64_64.AppImage.txt
```

Am I doing the verification wrong or is there a problem with the signatures?

**Comment by markblundeberg** [comment]
Generally with verifying detached gpg signatures you shouldn't need to specify the target filename, just the signature. In this case it looks like the .asc file names were modified, so yeah you DO have to give the filename manually.

Anyway, `JF.Electron-Cash-4.0.11-x86_64.AppImage.asc` is intended to be a signature over `Electron-Cash-4.0.11-x86_64.AppImage`, not the SHA256 text file.

**Comment by BigBlockIfTrue** [comment]
Thanks, the signatures verify.
